baseURL = 'https://oscar.cederberg.xyz'
languageCode = 'en-us'
title = 'oscarcederberg'
theme = 'cederberg'

[params]
  subtitle = 'knös fnös in darkness'

[menu]
  [[menu.main]]
    name = 'home'
    url = '/'
    weight = -100
  [[menu.main]]
    name = 'blog'
    url = '/posts/'
    weight = -90