baseURL = 'https://oscar.cederberg.xyz'
languageCode = 'en-us'
title = 'oscar.cederberg.xyz'
theme = 'cederberg'

[menu]
  [[menu.main]]
    name = 'home'
    url = '/'
    weight = -100
  [[menu.main]]
    name = 'blog'
    url = '/posts/'
    weight = -90